kind: pipeline
type: docker
name: default

steps:
  - name: check wallets
    image: node:18
    environment:
      DEV_WALLET:
        from_secret: oracle-factory-contract-owner-dev-privatekey
      PROD_WALLET:
        from_secret: oracle-factory-contract-owner-prod-privatekey
    commands:
      - npm i ethers@5
      - npm i -g ts-node
      - ts-node scripts/check-wallets.ts
