kind: pipeline
type: docker
name: default

trigger:
  event:
    exclude:
      - promote

steps:
  - name: install deps
    # fixed node version to work around https://github.com/NomicFoundation/hardhat/issues/3877
    image: node:18.12.1
    pull: always
    commands:
      - node -v
      - npm -v
      - npm ci

  - name: check format
    # fixed node version to work around https://github.com/NomicFoundation/hardhat/issues/3877
    image: node:18.12.1
    commands:
      - npm run check-format

  - name: compile
    # fixed node version to work around https://github.com/NomicFoundation/hardhat/issues/3877
    image: node:18.12.1
    commands:
      - npm run compile

  - name: test
    # fixed node version to work around https://github.com/NomicFoundation/hardhat/issues/3877
    image: node:18.12.1
    commands:
      - npm run test

  # # require iexec instance not present on hardhat chain
  # - name: dry-run native deployment
  #   # fixed node version to work around https://github.com/NomicFoundation/hardhat/issues/3877
  #   image: node:18.12.1
  #   commands:
  #     - npm run deploy-native

  - name: dry-run x-chain deployment
    # fixed node version to work around https://github.com/NomicFoundation/hardhat/issues/3877
    image: node:18.12.1
    commands:
      - npm run deploy-x-chain
